const { _electron: electron, expect } = require('playwright/test');
const path = require('node:path');
const fs = require('node:fs/promises');
const assert = require('node:assert/strict');
const root = path.resolve(__dirname, '..');
async function main() {
  const data = await fs.mkdtemp(path.join(require('node:os').tmpdir(), 'dsh-appearance-ui-'));
  const screenshots = path.join(root, '.test-data', 'appearance-screenshots'); await fs.mkdir(screenshots, { recursive: true });
  const env = { ...process.env, DSH_DESKTOP_TEST_DATA: data }; delete env.ELECTRON_RUN_AS_NODE;
  const packaged = process.argv.includes('--packaged');
  if (packaged) env.PATH = `${process.env.SystemRoot}\\System32;${process.env.SystemRoot}`;
  const launch = () => electron.launch({ executablePath: process.env.DSH_SMOKE_EXECUTABLE || (packaged ? path.join(root, `release/appearance-${require('../package.json').version}/win-unpacked/DeepSeek Harness Desktop.exe`) : require('electron')), args: packaged ? [] : [root], env, timeout: 60000 });
  let app = await launch();
  try {
    const page = await app.firstWindow(); const errors = []; page.on('pageerror', e => errors.push(e.message));
    await page.locator('#appearance').click();
    await page.locator('#appearance-feedback').filter({ hasText: '调整后自动保存' }).waitFor();
    await page.locator('[data-preset=glass]').click();
    await page.locator('#appearance-feedback').filter({ hasText: '已保存' }).waitFor();
    await expect(page.locator('html')).toHaveAttribute('data-appearance', 'glass');
    await page.screenshot({ path: path.join(screenshots, 'glass-light.png'), fullPage: true });
    await page.locator('#appearance-mode').selectOption('dark');
    await page.locator('#appearance-feedback').filter({ hasText: '已保存' }).waitFor();
    await page.screenshot({ path: path.join(screenshots, 'glass-dark.png'), fullPage: true });
    await page.locator('#appearance-lowEffects').check();
    await page.locator('#appearance-feedback').filter({ hasText: '已保存' }).waitFor();
    await expect(page.locator('#appearance-blur')).toBeDisabled();
    assert.equal(await page.locator('.appearance-layout .card').first().evaluate(el => getComputedStyle(el).backdropFilter), 'none');
    await page.locator('#appearance-lowEffects').uncheck();
    await page.locator('#appearance-feedback').filter({ hasText: '已保存' }).waitFor();
    await page.locator('#appearance-motion').selectOption('reduced');
    await page.locator('#appearance-feedback').filter({ hasText: '已保存' }).waitFor();
    assert.equal(await page.locator('#appearance-page').evaluate(el => getComputedStyle(el).animationName), 'none');
    const source = path.join(data, 'source.png'); await fs.copyFile(path.join(root, 'assets/icon.png'), source);
    await app.evaluate(({ dialog }, file) => { dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [file] }); }, source);
    await page.locator('#wallpaper-import').click(); await page.locator('#appearance-feedback').filter({ hasText: '已保存' }).waitFor();
    await fs.rm(source);
    const payload = await page.evaluate(() => window.desktop.action('appearance-read'));
    assert.equal(payload.settings.background, 'image'); assert.ok(payload.wallpaperUrl.startsWith('data:image/jpeg;base64,'));
    await page.locator('#status-short').filter({ hasText: /本地服务已就绪|需要处理/ }).waitFor({ timeout: 120000 });
    const state = await page.evaluate(() => window.desktop.state()); assert.equal(state.phase, 'ready', state.message);
    assert.equal(state.page, 'appearance', 'boot must not interrupt appearance edits');
    await page.locator('#appearance-motion').selectOption('full');
    await page.locator('#appearance-feedback').filter({ hasText: '已保存' }).waitFor();
    // Rapidly interrupt local pages and the separate workspace WebContentsView.
    await page.evaluate(async () => {
      for (const name of ['home', 'usage', 'workspace', 'appearance', 'workspace', 'home', 'appearance']) {
        await window.desktop.action(name);
        await new Promise(resolve => setTimeout(resolve, 24));
      }
    });
    await expect.poll(() => page.evaluate(async () => (await window.desktop.state()).page)).toBe('appearance');
    await expect.poll(() => page.evaluate(() => FluidMotion.activeCount)).toBe(0);
    assert.equal(await page.locator('#desktop-pages>main:not([hidden])').count(), 1);
    await expect(page.locator('#appearance-page')).toBeVisible();
    const workspace = app.context().pages().find(p => p.url().startsWith('http://127.0.0.1:'));
    await expect(workspace.locator('html')).toHaveAttribute('data-appearance', 'glass');
    await page.locator('#appearance-background').selectOption('gradient');
    await page.locator('#appearance-feedback').filter({ hasText: '已保存' }).waitFor();
    await page.locator('#workspace').click();
    const continueButton = workspace.getByRole('button', { name: '继续', exact: true });
    await workspace.locator('.pI_x6G_frame').waitFor({ timeout: 30000 });
    if (await continueButton.isVisible()) await continueButton.click();
    await workspace.waitForTimeout(1000);
    const skipKey = workspace.getByRole('button', { name: '稍后配置', exact: true });
    if (await skipKey.isVisible()) await skipKey.click();
    if (await continueButton.isVisible()) await continueButton.click();
    await workspace.screenshot({ path: path.join(screenshots, 'startup-dialogs.png') });
    await expect(workspace.locator('.pI_x6G_frame')).toHaveAttribute('data-fluid-layout', '');
    const initialWidth = await workspace.locator('.pI_x6G_sidebarCol').evaluate(el => el.getBoundingClientRect().width);
    await workspace.getByRole('button', { name: '收起侧边栏', exact: true }).click();
    const duringWidth = await workspace.locator('.pI_x6G_sidebarCol').evaluate(el => el.getBoundingClientRect().width);
    assert.ok(duringWidth > 56 && duringWidth <= initialWidth, `Sidebar should move continuously: ${duringWidth}`);
    await workspace.getByRole('button', { name: '打开侧边栏', exact: true }).click();
    await expect.poll(() => workspace.locator('.pI_x6G_sidebarCol').evaluate(el => Math.round(el.getBoundingClientRect().width))).toBe(Math.round(initialWidth));
    await workspace.getByRole('button', { name: '视图选项', exact: true }).click();
    await expect(workspace.getByRole('menu').first()).toBeVisible();
    await workspace.keyboard.press('Escape');
    await expect(workspace.getByRole('menu')).toHaveCount(0);
    await expect.poll(() => workspace.locator('[data-fluid-ghost]').count()).toBe(0);
    await expect(workspace.locator('body')).toHaveAttribute('data-ds-dark-theme', /.*/);
    await workspace.screenshot({ path: path.join(screenshots, 'workspace-glass.png') });
    console.log('Workspace theme:', await workspace.locator('body').evaluate(el => ({ scheme: getComputedStyle(el).colorScheme, color: getComputedStyle(el).color, background: getComputedStyle(el).getPropertyValue('--dsw-alias-bg-base') })));
    assert.equal(await workspace.evaluate(() => typeof window.desktop), 'undefined');
    await page.locator('#appearance').click();
    await page.locator('#usage').click();
    await page.screenshot({ path: path.join(screenshots, 'usage-dark.png'), fullPage: true });
    assert.equal(await page.locator('#usage-search').evaluate(el => getComputedStyle(el).backgroundColor), 'rgb(32, 39, 53)');
    await page.locator('#usage-pricing-open').click();
    await page.locator('#usage-pricing-dialog').waitFor();
    await page.evaluate(() => { FluidMotion.closeDialog(document.getElementById('usage-pricing-dialog')); FluidMotion.openDialog(document.getElementById('usage-pricing-dialog'), document.getElementById('usage-pricing-open')); });
    await expect.poll(() => page.evaluate(() => FluidMotion.activeCount)).toBe(0);
    await page.screenshot({ path: path.join(screenshots, 'pricing-dark.png') });
    await page.locator('#usage-pricing-close').click();
    await expect(page.locator('#usage-pricing-dialog')).not.toBeVisible();
    await page.locator('#home').click();
    await page.screenshot({ path: path.join(screenshots, 'management-dark.png'), fullPage: true });
    await page.locator('#appearance').click();
    const referenceOpened = app.waitForEvent('window');
    await page.locator('[data-action=design-reference]').click();
    const reference = await referenceOpened;
    await reference.locator('#reference-lens[data-liquid]').waitFor();
    assert.equal(await reference.evaluate(() => typeof window.desktop), 'undefined');
    await reference.close();
    await page.locator('#appearance-background').selectOption('image');
    await page.locator('#appearance-feedback').filter({ hasText: '已保存' }).waitFor();
    assert.deepEqual(errors, []);
    await app.close(); app = await launch();
    const reloaded = await app.firstWindow(); await reloaded.locator('#appearance').click();
    await reloaded.locator('#appearance-feedback').filter({ hasText: '调整后自动保存' }).waitFor();
    await expect(reloaded.locator('html')).toHaveAttribute('data-scheme', 'dark');
    await expect(reloaded.locator('#appearance-background')).toHaveValue('image');
    assert.ok((await reloaded.evaluate(() => window.desktop.action('appearance-read'))).wallpaperUrl);
    await reloaded.locator('#appearance-reset').click(); await reloaded.locator('#appearance-feedback').filter({ hasText: '已保存' }).waitFor();
    await expect(reloaded.locator('html')).toHaveAttribute('data-appearance', 'classic');
    console.log('Appearance smoke passed:', screenshots);
  } finally { await app.close(); }
}
main().catch(error => { console.error(error); process.exitCode = 1; });
